### PR TITLE
Space out buttons in profile view

### PR DESCRIPTION
**Pull request by rimorin**

### CODE REVIEW

**Comment by rimorin** [comment]
@Fauxicing upon creating a pull request, cloud flare will create a test environment that is based on the branch name. You can click on the details and get the link.

**Comment by rimorin** [comment]
@Fauxicing try testing the fix and if its good, pls "Merge pull request" and its will be merge to our staging environment.

**Comment by rimorin** [comment]
Screenshot 2023-02-16 at 11 44 46 PM

new view

**Comment by rimorin** [comment]
Screenshot 2023-02-16 at 11 48 54 PM

When you click on the cloud flare details, you'll see the link to the branch.

**Comment by Fauxicing** [comment]
Sorry @rimorin I don't see the changes? What buttons is supposed to be spaced out? Do I still pull?? x_x

**Comment by Fauxicing** [comment]
https://user-images.githubusercontent.com/125553437/219423146-c0fcd8bd-043b-49e6-828a-3ba0bcde7807.mov

**Comment by rimorin** [comment]
Sorry I paste the wrong image. It should be the "my profile" view. The one w the gear ⚙️ image.

**Comment by Fauxicing** [comment]
Oh ok got it, no worries. Yup it works, will pull now, thanks!

**Comment by rimorin** [comment]
Another thing. Once a feature branch like profilealignment is tested and good for merge, you can delete it. @Fauxicing

**Comment by rimorin** [comment]
You should be able to see the msg, "You’re all set—the profilealignment branch can be safely deleted."

**Comment by Fauxicing** [comment]
Alright noted, thanks!

**Pull request merged**
